### PR TITLE
Add ability to handle Win10 SSH requests

### PR DESCRIPTION
**Pull request by Doridian**
This adds the ability to handle SSH agent proxying to the native Windows 10 "optional feature" OpenSSH client.

### CODE REVIEW

**Comment by cuihaoleo** [comment]
Nice feature.

I compiled your code but find it not work. I think the new code is incomplete. `WSLClient::IsConnected` throws exception and client handler never run into main loop of `SSHAgentClient::ServiceSocket`.

Don't know about C#. I simply rewrited `WSLClient::IsConnected` to let it return true. Now the program runs as is expected. Could you please check your code?

**Comment by Doridian** [comment]
And you would be totally right. I have now fixed `IsConnected` to return correct result (`client.Connected`).
No idea how I never noticed this.

**Comment by PromoFaux** [comment]
Hi @Doridian , banging my head against the wall a bit here!

I _think_ i managed to compile your code, (Not much experience with `dotnet core`, but it appears to run) however it throws exceptions whenever I run `ssh-add -l` from windows, any pointers would be appreciated.

```text
C:\bin\wsl-ssh-pageant>wsl-ssh-pageant.exe --winssh ssh-pageant
Listening for Win10 OpenSSH connections on \\.\pipe\ssh-pageant
WslSSHPageant.PageantException: WM_COPYDATA failed
   at WslSSHPageant.PageantHandler.Query(ArraySegment`1 buf) in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\PageantHandler.cs:line 126
   at WslSSHPageant.SSHAgentClient.<ServiceSocket>d__7.MoveNext() in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\SSHAgentClient.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WslSSHPageant.SSHAgentClient.<WorkSocket>d__6.MoveNext() in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\SSHAgentClient.cs:line 57
WslSSHPageant.PageantException: WM_COPYDATA failed
   at WslSSHPageant.PageantHandler.Query(ArraySegment`1 buf) in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\PageantHandler.cs:line 126
   at WslSSHPageant.SSHAgentClient.<ServiceSocket>d__7.MoveNext() in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\SSHAgentClient.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WslSSHPageant.SSHAgentClient.<WorkSocket>d__6.MoveNext() in C:\Users\awarner\Source\Repos\wsl-ssh-pageant\SSHAgentClient.cs:line 57
```

**Comment by Doridian** [comment]
@PromoFaux To me that reads like you aren't running an SSH agent for this to connect to.
Such as pageant or gpg-agent with putty/ssh support enabled.
Please do keep in mind this is only a proxy and not a self-contained SSH agent

**Comment by PromoFaux** [comment]
I'm running `gpg-agent` with putty support, which seems to work in WSL with `weasel-pageant` 

I've tried a combination of `enable-putty-support`/`enable-ssh-support` and both at the same time, but still no joy. Have also tried knocking `weasel-pageant` out of the equation in case it was interfering, but still the same results.

**Comment by Doridian** [comment]
@PromoFaux That is odd. I just compared the code that throws this error with the code used in weasel-pageant. And behaviour-wise it seems to be the exact same except for `FindWindow`. I also use gpg-agent myself, so I know it does work for met.
I have added a commit that makes the `FindWindow` call the same. Try pulling and seeing if that fixes your problem.

**Comment by PromoFaux** [comment]
No joy i'm afraid!

**Comment by PromoFaux** [comment]
Spits out the same error I'm afraid. 

In order to get it to run in the first place, I needed to do a `dotnet publish -c Release`, as after installing several versions of the dotnet core runtime/SDK on the target computer, I was still getting errors about missing libraries....

```
:\Users\awarner>gpg --version
gpg (GnuPG) 2.2.10
libgcrypt 1.8.3
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: C:/Users/awarner/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

C:\Users\awarner>gpg-agent --version
gpg-agent (GnuPG) 2.2.10
libgcrypt 1.8.3
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Doridian** [comment]
@PromoFaux 
Yeah, dotnet core needs publishes, even if you install framework. The only way to get core to run is by either using a published version or installing VS2017 on the target machine and building it locally.

Feel free to try to swap it to .NET Framework and recompile it, see if that fixes anything.
I am sadly out of ideas at this point otherwise :(

**Comment by PromoFaux** [comment]
I've actually found another fork that attempts to do the same thing (https://github.com/btolfa/pipe-ssh-pageant), that doesn't throw any exceptions, but I get `error fetching identities: invalid format` when running `ssh-add -l`

I think maybe I'll have to give up on the dream of using my yubi as sole SSH authentication and continue running separate keypairs per machine. Sigh!

**Comment by PromoFaux** [comment]
@Doridian, Just FYI, tried your stuff on another PC and it works without issue. Can only assume there is something wrong with the other one!

**Comment by benpye** [comment]
Hey, finally had time to look at this, looks good. Thanks!

**Pull request merged**
